<?php

use Illuminate\Database\Seeder;

class ManufactureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $man = [
            ['id'=>'100', 'name'=>'PT. Heinz ABC Indonesia'],
            ['id'=>'101', 'name'=>'PT. Buana Tirta Utama'],
            ['id'=>'102', 'name'=>'PT. Mayora Indah Tbk'],
            ['id'=>'103', 'name'=>'PT. Mega Global Food Industry'],
            ['id'=>'104', 'name'=>'PT. Ultra Prima Abadi'],
            ['id'=>'105', 'name'=>'PT. Monysaga Prima'],
            ['id'=>'106', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'107', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'108', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'13', 'name'=>'PT. Keong Nusantara Abadi'],
            ['id'=>'14', 'name'=>'PT. Ultrajaya Milk Industry'],
            ['id'=>'15', 'name'=>'PT. Tirta Alam Segar'],
            ['id'=>'16', 'name'=>'PT. Santos Jaya Abadi'],
            ['id'=>'17', 'name'=>'PT. Dua Kelinci'],
            ['id'=>'18', 'name'=>'PT. YHS Indonesia'],
            ['id'=>'19', 'name'=>'PT. Dalya Citramandiri'],
            ['id'=>'2', 'name'=>'PT. Sinar Kencana Agung'],
            ['id'=>'20', 'name'=>'PT. General Food Industries Bandung'],
            ['id'=>'21', 'name'=>'PT. Indofood'],
            ['id'=>'22', 'name'=>'PT. Yakult Indonesia Persada'],
            ['id'=>'23', 'name'=>'PT. Monysaga Prima'],
            ['id'=>'24', 'name'=>'PT. Unilever Indonesia Tbk'],
            ['id'=>'25', 'name'=>'PT. SMART TBK'],
            ['id'=>'26', 'name'=>'PT. Salim Ivomas Pratama Tbk'],
            ['id'=>'27', 'name'=>'PT. Monysaga Prima'],
            ['id'=>'28', 'name'=>'PT. Monde Mahkota Biskuit'],
            ['id'=>'29', 'name'=>'PT. Perusahaan Industri Ceres'],
            ['id'=>'3', 'name'=>'PT. Nissin Biscuit Indonesia'],
            ['id'=>'30', 'name'=>'PT. Ultra Prima Abadi'],
            ['id'=>'31', 'name'=>'PT. Santos Jaya Abadi'],
            ['id'=>'32', 'name'=>'PT. So Good Food Manufacturing'],
            ['id'=>'33', 'name'=>'PT. Unilever Indonesia Tbk'],
            ['id'=>'34', 'name'=>'PT. Coca Cola Bottling Indonesia'],
            ['id'=>'35', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'36', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'37', 'name'=>'PT. Dellifood Sentosa Corpindo'],
            ['id'=>'38', 'name'=>'PT. General Food Industries Bandung'],
            ['id'=>'39', 'name'=>'PT. Santos Jaya Abadi'],
            ['id'=>'4', 'name'=>'PT. Unilever Indonesia Tbk'],
            ['id'=>'40', 'name'=>'PT. Marizarasa Sarimurni (Factory 2)'],
            ['id'=>'41', 'name'=>'PT. Unilever Indonesia Tbk'],
            ['id'=>'42', 'name'=>'PT. Nirwana Lestari'],
            ['id'=>'43', 'name'=>'PT. Keong Nusantara Abadi'],
            ['id'=>'44', 'name'=>'PT. Ikafood Putamas'],
            ['id'=>'45', 'name'=>'PT. Mayora Indah Tbk'],
            ['id'=>'46', 'name'=>'PT. Unilever Indonesia Tbk'],
            ['id'=>'47', 'name'=>'PT. Forisa Nusapersada'],
            ['id'=>'48', 'name'=>'PT. Frisian Flag Indonesia'],
            ['id'=>'49', 'name'=>'PT. Industri Jamu & Farmasi Sidomuncul'],
            ['id'=>'5', 'name'=>'PT. Arnott`s Indonesia'],
            ['id'=>'50', 'name'=>'PT. Indolakto'],
            ['id'=>'51', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'52', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'53', 'name'=>'PT. Torabika Eka Semesta'],
            ['id'=>'54', 'name'=>'PT. Torabika Eka Semesta'],
            ['id'=>'55', 'name'=>'PT. Riau Sakti United Plantation'],
            ['id'=>'56', 'name'=>'PT. ABC President Indonesia'],
            ['id'=>'57', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'58', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'59', 'name'=>'PT. Santos Jaya Abadi'],
            ['id'=>'60', 'name'=>'PT. Bina Karya Prima'],
            ['id'=>'61', 'name'=>'PT. Indolakto'],
            ['id'=>'62', 'name'=>'PT. Pulau Sambu'],
            ['id'=>'63', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'64', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'65', 'name'=>'PT. Ultrajaya Milk Industry & Trading Co.Tbk'],
            ['id'=>'66', 'name'=>'PT. Ultrajaya Milk Industry & Trading Co.Tbk'],
            ['id'=>'67', 'name'=>'PT. Nippon Indosari Corpindo, Tbk'],
            ['id'=>'68', 'name'=>'PT. Perusahaan Industri Ceres'],
            ['id'=>'69', 'name'=>'PT. Perusahaan Industri Ceres'],
            ['id'=>'70', 'name'=>'PT. Indofood CBP Sukses Makmur Tbk'],
            ['id'=>'71', 'name'=>'PT. Nutrifood Indonesia, Raya Ciawi '],
            ['id'=>'72', 'name'=>'PT. Industri Jamu & Farmasi Sidomuncul'],
            ['id'=>'73', 'name'=>'PT. Nestle Indonesia'],
            ['id'=>'74', 'name'=>'PT. Nestle Indonesia'],
            ['id'=>'75', 'name'=>'PT. Frisian Flag Indonesia'],
            ['id'=>'76', 'name'=>'PT. Makindo Perdana '],
            ['id'=>'77', 'name'=>'PT. Nutrifood Indonesia'],
            ['id'=>'78', 'name'=>'PT. Simba Indosnack Makmur'],
            ['id'=>'79', 'name'=>'PT. Torabika Eka Semesta'],
            ['id'=>'80', 'name'=>'PT. Lotte Indonesia'],
            ['id'=>'81', 'name'=>'PT. Arnott`s Indonesia'],
            ['id'=>'82', 'name'=>'PT. Ultra Prima Abadi'],
            ['id'=>'83', 'name'=>'PT. Mayora Indah Tbk'],
            ['id'=>'84', 'name'=>'PT. Arnott`s Indonesia'],
            ['id'=>'85', 'name'=>'PT. Nissin Biscuit Indonesia'],
            ['id'=>'86', 'name'=>'PT. Nirwana Lestari'],
            ['id'=>'87', 'name'=>'PT. Hale International'],
            ['id'=>'88', 'name'=>'PT. Kalbe'],
            ['id'=>'89', 'name'=>'PT. Hokkan Indonesia'],
            ['id'=>'90', 'name'=>'PT. Kaldu Sari Nabati Indonesia'],
            ['id'=>'91', 'name'=>'PT. Kaldu Sari Nabati Indonesia'],
            ['id'=>'92', 'name'=>'PT. Segarindo Primajaya'],
            ['id'=>'93', 'name'=>'PT. Matahari Putra'],
            ['id'=>'94', 'name'=>'PT. Asiacapital Utama Indonesia'],
            ['id'=>'95', 'name'=>'PT. Unimos'],
            ['id'=>'96', 'name'=>'PT. Jadi Abadi Corak Biscuit Factory Indonesia'],
            ['id'=>'97', 'name'=>'PT. Unimos'],
            ['id'=>'98', 'name'=>'PT. Unimos'],
            ['id'=>'99', 'name'=>'PT. Jeinz ABC Indonesia']
        ];

        // masukkan data ke database
        DB::table('manufactures')->insert($man);

        $product_man = [
            ['foodProduct_id'=>'100', 'manufacture_id'=>'100'],
            ['foodProduct_id'=>'101', 'manufacture_id'=>'101'],
            ['foodProduct_id'=>'102', 'manufacture_id'=>'102'],
            ['foodProduct_id'=>'103', 'manufacture_id'=>'103'],
            ['foodProduct_id'=>'104', 'manufacture_id'=>'104'],
            ['foodProduct_id'=>'105', 'manufacture_id'=>'105'],
            ['foodProduct_id'=>'106', 'manufacture_id'=>'106'],
            ['foodProduct_id'=>'107', 'manufacture_id'=>'107'],
            ['foodProduct_id'=>'107', 'manufacture_id'=>'108'],
            ['foodProduct_id'=>'13', 'manufacture_id'=>'13'],
            ['foodProduct_id'=>'14', 'manufacture_id'=>'14'],
            ['foodProduct_id'=>'15', 'manufacture_id'=>'15'],
            ['foodProduct_id'=>'16', 'manufacture_id'=>'16'],
            ['foodProduct_id'=>'17', 'manufacture_id'=>'17'],
            ['foodProduct_id'=>'18', 'manufacture_id'=>'18'],
            ['foodProduct_id'=>'19', 'manufacture_id'=>'19'],
            ['foodProduct_id'=>'2', 'manufacture_id'=>'2'],
            ['foodProduct_id'=>'20', 'manufacture_id'=>'20'],
            ['foodProduct_id'=>'21', 'manufacture_id'=>'21'],
            ['foodProduct_id'=>'22', 'manufacture_id'=>'22'],
            ['foodProduct_id'=>'23', 'manufacture_id'=>'23'],
            ['foodProduct_id'=>'24', 'manufacture_id'=>'24'],
            ['foodProduct_id'=>'25', 'manufacture_id'=>'25'],
            ['foodProduct_id'=>'26', 'manufacture_id'=>'26'],
            ['foodProduct_id'=>'27', 'manufacture_id'=>'27'],
            ['foodProduct_id'=>'28', 'manufacture_id'=>'28'],
            ['foodProduct_id'=>'29', 'manufacture_id'=>'29'],
            ['foodProduct_id'=>'3', 'manufacture_id'=>'3'],
            ['foodProduct_id'=>'30', 'manufacture_id'=>'30'],
            ['foodProduct_id'=>'31', 'manufacture_id'=>'31'],
            ['foodProduct_id'=>'32', 'manufacture_id'=>'32'],
            ['foodProduct_id'=>'33', 'manufacture_id'=>'33'],
            ['foodProduct_id'=>'34', 'manufacture_id'=>'34'],
            ['foodProduct_id'=>'35', 'manufacture_id'=>'35'],
            ['foodProduct_id'=>'36', 'manufacture_id'=>'36'],
            ['foodProduct_id'=>'37', 'manufacture_id'=>'37'],
            ['foodProduct_id'=>'38', 'manufacture_id'=>'38'],
            ['foodProduct_id'=>'39', 'manufacture_id'=>'39'],
            ['foodProduct_id'=>'4', 'manufacture_id'=>'4'],
            ['foodProduct_id'=>'40', 'manufacture_id'=>'40'],
            ['foodProduct_id'=>'41', 'manufacture_id'=>'41'],
            ['foodProduct_id'=>'42', 'manufacture_id'=>'42'],
            ['foodProduct_id'=>'43', 'manufacture_id'=>'43'],
            ['foodProduct_id'=>'44', 'manufacture_id'=>'44'],
            ['foodProduct_id'=>'45', 'manufacture_id'=>'45'],
            ['foodProduct_id'=>'46', 'manufacture_id'=>'46'],
            ['foodProduct_id'=>'47', 'manufacture_id'=>'47'],
            ['foodProduct_id'=>'48', 'manufacture_id'=>'48'],
            ['foodProduct_id'=>'49', 'manufacture_id'=>'49'],
            ['foodProduct_id'=>'5', 'manufacture_id'=>'5'],
            ['foodProduct_id'=>'50', 'manufacture_id'=>'50'],
            ['foodProduct_id'=>'51', 'manufacture_id'=>'51'],
            ['foodProduct_id'=>'52', 'manufacture_id'=>'52'],
            ['foodProduct_id'=>'53', 'manufacture_id'=>'53'],
            ['foodProduct_id'=>'54', 'manufacture_id'=>'54'],
            ['foodProduct_id'=>'55', 'manufacture_id'=>'55'],
            ['foodProduct_id'=>'56', 'manufacture_id'=>'56'],
            ['foodProduct_id'=>'57', 'manufacture_id'=>'57'],
            ['foodProduct_id'=>'58', 'manufacture_id'=>'58'],
            ['foodProduct_id'=>'59', 'manufacture_id'=>'59'],
            ['foodProduct_id'=>'60', 'manufacture_id'=>'60'],
            ['foodProduct_id'=>'61', 'manufacture_id'=>'61'],
            ['foodProduct_id'=>'62', 'manufacture_id'=>'62'],
            ['foodProduct_id'=>'63', 'manufacture_id'=>'63'],
            ['foodProduct_id'=>'64', 'manufacture_id'=>'64'],
            ['foodProduct_id'=>'65', 'manufacture_id'=>'65'],
            ['foodProduct_id'=>'66', 'manufacture_id'=>'66'],
            ['foodProduct_id'=>'67', 'manufacture_id'=>'67'],
            ['foodProduct_id'=>'68', 'manufacture_id'=>'68'],
            ['foodProduct_id'=>'69', 'manufacture_id'=>'69'],
            ['foodProduct_id'=>'70', 'manufacture_id'=>'70'],
            ['foodProduct_id'=>'71', 'manufacture_id'=>'71'],
            ['foodProduct_id'=>'72', 'manufacture_id'=>'72'],
            ['foodProduct_id'=>'73', 'manufacture_id'=>'73'],
            ['foodProduct_id'=>'74', 'manufacture_id'=>'74'],
            ['foodProduct_id'=>'75', 'manufacture_id'=>'75'],
            ['foodProduct_id'=>'76', 'manufacture_id'=>'76'],
            ['foodProduct_id'=>'77', 'manufacture_id'=>'77'],
            ['foodProduct_id'=>'78', 'manufacture_id'=>'78'],
            ['foodProduct_id'=>'79', 'manufacture_id'=>'79'],
            ['foodProduct_id'=>'80', 'manufacture_id'=>'80'],
            ['foodProduct_id'=>'81', 'manufacture_id'=>'81'],
            ['foodProduct_id'=>'82', 'manufacture_id'=>'82'],
            ['foodProduct_id'=>'83', 'manufacture_id'=>'83'],
            ['foodProduct_id'=>'84', 'manufacture_id'=>'84'],
            ['foodProduct_id'=>'85', 'manufacture_id'=>'85'],
            ['foodProduct_id'=>'86', 'manufacture_id'=>'86'],
            ['foodProduct_id'=>'87', 'manufacture_id'=>'87'],
            ['foodProduct_id'=>'88', 'manufacture_id'=>'88'],
            ['foodProduct_id'=>'89', 'manufacture_id'=>'89'],
            ['foodProduct_id'=>'90', 'manufacture_id'=>'90'],
            ['foodProduct_id'=>'91', 'manufacture_id'=>'91'],
            ['foodProduct_id'=>'92', 'manufacture_id'=>'92'],
            ['foodProduct_id'=>'93', 'manufacture_id'=>'93'],
            ['foodProduct_id'=>'94', 'manufacture_id'=>'94'],
            ['foodProduct_id'=>'95', 'manufacture_id'=>'95'],
            ['foodProduct_id'=>'96', 'manufacture_id'=>'96'],
            ['foodProduct_id'=>'97', 'manufacture_id'=>'97'],
            ['foodProduct_id'=>'98', 'manufacture_id'=>'98'],
            ['foodProduct_id'=>'99', 'manufacture_id'=>'99']
        ];

        // masukkan data ke database
        DB::table('foodproduct_manufacture')->insert($product_man);
    }
}
